language: java

install:
  - cd ..
  - "git clone https://github.com/hnfhtw/mail-verify-backend.git"

script:
  - "cd mail-verify-uml"
  - "mvn org.eclipse.acceleo:org.eclipse.acceleo.maven.launcher:acceleo-launcher"

after_success:
  - "cd ../mail-verify-backend"
  - "git add -A ."
  - git commit -m "Update generated code"
  - git push -f -q https://hnfhtw:$GITHUB_API_KEY@github.com/hnfhtw/mail-verify-backend.git master
